### PR TITLE
Marie lataretu/issue30

### PR DESCRIPTION
**Pull request by MarieLataretu**
- create and publish fai index for host, control, own and/or rRNA

### CODE REVIEW

**Comment by hoelzer** [comment]
```
nextflow run clean.nf --fasta /home/martin/tmp/2021-03-05_clean_cpsittaci_for_yeast/se/cps_GR9/01-Assembly/cps_GR9_polished.fasta --control phix --cores 4 --max_cores 8        
```

```
Process `clean_fasta:concat_contamination` declares 3 input channels but 2 were specified
```

?

**Comment by MarieLataretu** [comment]
args, I missed the fasta part somehow.

It should work now :)

**Comment by hoelzer** [comment]
runs now though :) 

but:
```
nextflow run clean.nf --fasta /home/martin/tmp/2021-03-05_clean_cpsittaci_for_yeast/se/cps_GR9/01-Assembly/cps_GR9_polished.fasta --control phix --cores 4 --max_cores 8
...
executor >  local (4)
[20/f78425] process > clean_fasta:concat_contamination (1) [100%] 1 of 1 ✔
[f0/146bee] process > clean_fasta:minimap2_fasta (1)       [100%] 1 of 1 ✔
[3c/2ce3b9] process > clean_fasta:writeLog (1)             [100%] 1 of 1 ✔
[02/ba7ba7] process > clean_fasta:minimap2Stats (1)        [100%] 1 of 1 ✔

(igv) ➜  clean git:(MarieLataretu/issue30) ✗ tree results 
results
├── cps_GR9_polished
│   └── minimap2
│       ├── cps_GR9_polished.contamination.sorted.bam
│       ├── cps_GR9_polished.contamination.sorted.bam.bai
│       ├── db.fa.gz
│       ├── db.fa.gz.fai
│       ├── log.txt
│       └── stats.txt
└── Logs
    ├── execution_report.html
    └── execution_timeline.html

3 directories, 8 files
```

* I think a gzipped db file is problematic e.g. for usage in IGV, ... ? 
* there are no "clean" and "contamination" output FASTAs? Similar to the output FASTQs? 

I also run a test w/ some FASTQ where it looks fine and I get what I expect:

* contamination BAM w/ index
* FASTQ for clean and contamination
* the db index (gzipped again, which might be difficult?)

```
nextflow run clean.nf --illumina_single_end small.fastq.gz --control phix --cores 4 --max_cores 8
...
(igv) ➜  clean git:(MarieLataretu/issue30) ✗ tree results/small 
results/small
└── minimap2
    ├── db.fa.gz
    ├── db.fa.gz.fai
    ├── log.txt
    ├── small.clean.fastq.gz
    ├── small.contamination.fastq.gz
    ├── small.contamination.sorted.bam
    ├── small.contamination.sorted.bam.bai
    └── stats.txt

1 directory, 8 files
```

So in short:

1) gzipped db index? better provide unzipped, or? But can be large... maybe only output optionally via a parameter
2) output FASTAs? for FASTA input?

**Comment by MarieLataretu** [comment]
1)
- I just checked the index and it is not actually compressed, just named 'gz' - I changed that. 
- `samtools faidx` produces also a compressed index file`gzi` for the use with `gz` files - this is also published now.

So we have now: `db.fa.gz`, `db.fa.gz.gzi` and `db.fa.fai`. IGV can't work with `db.fa.gz`... But I'm not sure if it is necessary to provide a parameter `--extract_contamination` (or something), if there is a `.gz` which can be extracted by the user.
2) done

**Comment by hoelzer** [comment]
> So we have now: `db.fa.gz`, `db.fa.gz.gzi` and `db.fa.fai`. IGV can't work with `db.fa.gz`... But I'm not sure if it is necessary to provide a parameter `--extract_contamination` (or something), if there is a `.gz` which can be extracted by the user.

Okay, that's true! if the user wants to look at the BAM and needs the indexed FASTA he can extract it. Likely something for the README page then. 

Ready to merge I would say!

**Pull request merged**
