### PR TITLE
Multiqc

### LINKED ISSUE #22: MultiQC support
* fastQC (has multiQC support)
* nanoPlot
    * currently no multiQC support, just provide a PNG figure 
    * https://github.com/hoelzer/mgnify-lr/blob/master/modules/nanoplot.nf
* bbmap (has multiQC support)
* minimap2 (currently no multiQC support, maybe just provide summary file)
* write own multiQC support for the final log.stats file (show some bar plots)

### PR DESCRIPTION
**Pull request by MarieLataretu**
- creates one MultiQC report per run
- FastQC, Quast and NanoPlot support 

fixes #22 

I tested only conda so far!

### CODE REVIEW

**Comment by hoelzer** [comment]
```
Deprecated syntax error - replace `includeInputs true` with `, includeInputs: true` 
```

seems there was a syntax problem, I fixed that and running tests now

**Comment by hoelzer** [comment]
```
Deprecated syntax error - replace `includeInputs true` with `, includeInputs: true` 
```

seems there was a syntax problem, I fixed that and running tests now

**Comment by hoelzer** [comment]
I also replaced few containers --> it's better when all (most) use the same baseimage to save storage (_container slices_)

**Review by hoelzer — APPROVED** [review]
nice!

cool also the better sub-workflow modularization (y)

**Comment by MarieLataretu** [comment]
@containers nice!

@quast yes, it is for empty input for quast. Did you check the MultiQC report? If it's fine, I'd merge

**Comment by hoelzer** [comment]
yep, the report was fine for me!

**Pull request merged**
