### PR TITLE
Marie lataretu/issue23

### PR DESCRIPTION
**Pull request by MarieLataretu**
- modularized alignment handling for easy bam file filtering
- bam soft-clipped filter option: 
  - by the total number of soft-clipped positions or 
  - relative number of soft-clipped positions (relative to the read length)

### CODE REVIEW

**Review by hoelzer — APPROVED** [review]
cool @MarieLataretu !

So one main part is now the additional script you wrote to identify soft-clipped reads? I think that's really a feature others are lacking or can not consider if they just run `minimap2` and some downstream commands manually. So that's cool. 

You added this to prevent false read mappings just bc/ `minimap2` soft clips huge parts of a read to get it somehow aligned to the reference?

**Comment by hoelzer** [comment]
> We saw that in at least one test data set. So with the soft-clip parameter, one can filter the reads more stringent by not trusting the mapped reads with lots of soft-clipped nts.

cool!

**Comment by MarieLataretu** [comment]
Should work now :)

Feel free to test or merge directly!

**Comment by hoelzer** [comment]
cool, in the advent of buisiness - I merge :D We anyway need to do then a larger master merge and testing for a release I guess

**Pull request merged**
